---

# Manage current archive of gpg keys

- name: Export system archive GPG keys
  become: True
  become_user: "{{ aptly_user }}"
  become_method: "{{ aptly_become_method }}"
  command: >
    gpg --no-default-keyring --keyring
    /usr/share/keyrings/{{ ansible_distribution | lower }}-archive-keyring.gpg
    --export --output /tmp/{{ aptly_system_archive_gpg_keys_keyring }}
  changed_when: False
  when: "{{ aptly_system_archive_gpg_keys_import == True }}"

- name: Import system archive GPG keys
  become: True
  become_user: "{{ aptly_user }}"
  become_method: "{{ aptly_become_method }}"
  command: >
    gpg --no-default-keyring
    --keyring {{ aptly_system_archive_gpg_keys_keyring }} --import
    /tmp/{{ aptly_system_archive_gpg_keys_keyring }}
  register: aptly_archive_gpg_keys_added
  changed_when: False
  when: "{{ aptly_system_archive_gpg_keys_import == True }}"

- name: Remove temp archive gpg export
  become: True
  file:
    dest: "/tmp/{{ aptly_system_archive_gpg_keys_keyring }}"
    state: 'absent'
  changed_when: False

- name: Check if new GPG key managed
  command: 'echo "New GPG key"'
  when:
    - "{{ aptly_system_archive_gpg_keys_import == True }}"
    - "{{ aptly_archive_gpg_keys_added.result.stderr is defined }}"
    - "{{ aptly_archive_gpg_keys_added.result.stderr.find(' changed:') != -1 }}"

